# Example DLP policy configuration for financial data protection
policies:
  - name: "Financial Data Protection"
    mode: "Enable"  # Enable, Test, or Disable
    priority: 1
    description: "Protects financial data from unauthorized sharing"
    
    # Policy scope - use string identifiers (e.g. "All")
    scope:
      exchange: ["All"]
      sharepoint: ["All"]
      onedrive: ["All"]
      teams: ["All"]
      devices: ["All"]
      
    # Policy rules
    rules:
      - name: "Credit Card Rule"
        conditions:
          - type: "ContentContainsPattern"
            pattern: "CreditCardNumber"
            minCount: 1
            
          - type: "RecipientDomain"
            operator: "NotEquals"
            value: "contoso.com"
            
        actions:
          - type: "BlockAccess"
            notifyUser: true
            notifyAdmin: true
            
      - name: "Banking Information Rule"
        conditions:
          - type: "SensitiveInfoType"
            infoType: "Australia Bank Account Number"
            minCount: 1
            
        actions:
          - type: "BlockAccess"
            notifyUser: true
            notifyAdmin: true